# @module ssh
# @summary SSH config assembly from ~/.ssh/config.d, host listing, key
#          generation, and EasySSH-driven inventory refresh.
#
# The generated ~/.ssh/config is a concatenation of a fixed header and every
# *.config fragment in $SSH_CONFIG_D. Nothing here runs at source time — the
# previous version regenerated your ssh config on every shell start and threw
# away hand edits.

require ssh ssh-keygen || return 0

# Where the config fragments live, and where generated keys are dropped.
SSH_CONFIG_D="${SSH_CONFIG_D:-$HOME/.ssh/config.d}"
SSH_KEYGEN_OUT_DIR="${SSH_KEYGEN_OUT_DIR:-$HOME/.ssh/generated}"

# ------------------------------------------------------------------ config ---

# @describe Rebuild ~/.ssh/config from the fragments in $SSH_CONFIG_D. The
#           previous config is kept as a timestamped backup next to it, so a
#           mistaken run is always recoverable. Explicit command only — this is
#           never run automatically.
# @usage    ssh_refresh_config
# @example  ssh_refresh_config
# @requires ssh
# @danger   Replaces ~/.ssh/config. Hand edits made directly to that file are
#           lost; put them in $SSH_CONFIG_D/*.config instead. A backup is
#           written to ~/.ssh/config.<timestamp>.bak first.
# @see      ssh_generate_host_config
# @os       any
ssh_refresh_config() {
    local config="$HOME/.ssh/config"
    local backup fragment found=0

    mkdir -p "$SSH_CONFIG_D" || return 1

    if [ -e "$config" ]; then
        backup="$config.$(timestamp).bak"
        cp -p "$config" "$backup" || {
            log_error "ssh_refresh_config: could not back up $config"
            return 1
        }
        log_info "backed up $config -> $backup"
    fi

    {
        printf '# generated by ssh_refresh_config on %s\n' "$(date)"
        printf '# edit the fragments in %s, never this file\n\n' "$SSH_CONFIG_D"
        printf 'Host *\n'
        printf '  ControlMaster auto\n'
        printf '  ControlPersist 600\n'
        printf '  ForwardAgent true\n\n'
    } > "$config" || return 1

    for fragment in "$SSH_CONFIG_D"/*.config; do
        [ -f "$fragment" ] || continue
        found=1
        printf '# --- %s ---\n' "${fragment##*/}" >> "$config"
        cat "$fragment" >> "$config"
        printf '\n' >> "$config"
    done

    chmod 600 "$config" 2>/dev/null

    if [ "$found" -eq 0 ]; then
        log_warn "no *.config fragments in $SSH_CONFIG_D — wrote header only"
    fi
    log_ok "rebuilt $config"
}

# @describe Print the Host names of production app/worker entries in
#           ~/.ssh/config.
# @usage    ssh_list_hosts
# @example  ssh_list_hosts | wc -l
# @os       any
ssh_list_hosts() {
    local config="$HOME/.ssh/config"
    [ -r "$config" ] || { log_error "ssh_list_hosts: cannot read $config"; return 1; }
    awk '/prod-worker/ || /prod-app/ || /production-app/ || /production-worker/ { print $2 }' \
        "$config"
}

# @describe Print production hosts whose name matches a pattern.
# @usage    ssh_list_hosts_matching [pattern]
# @example  ssh_list_hosts_matching client
# @see      ssh_list_hosts
# @os       any
ssh_list_hosts_matching() {
    local pattern="${1:-client}"
    ssh_list_hosts | grep -i -- "$pattern"
}

# ------------------------------------------------------------------- keys -----

# @describe Generate a passphrase-less 4096-bit RSA keypair for an application
#           under $SSH_KEYGEN_OUT_DIR (default ~/.ssh/generated, mode 700).
# @usage    ssh_generate_key <application-name>
# @example  ssh_generate_key billing-deploy
# @requires ssh-keygen
# @danger   Writes an unencrypted private key to disk. Refuses to overwrite an
#           existing key of the same name.
# @os       any
ssh_generate_key() {
    local app="$1" out
    [ -n "$app" ] || { log_error "usage: ssh_generate_key <application-name>"; return 1; }

    mkdir -p "$SSH_KEYGEN_OUT_DIR" || return 1
    chmod 700 "$SSH_KEYGEN_OUT_DIR" 2>/dev/null
    out="$SSH_KEYGEN_OUT_DIR/$app"

    if [ -e "$out" ]; then
        log_error "ssh_generate_key: $out already exists, refusing to overwrite"
        return 1
    fi
    ssh-keygen -t rsa -b 4096 -C "$app" -f "$out" -N ""
}

# @describe Generate a keypair for every name in $APPLICATION_LIST.
# @usage    ssh_generate_keys_all
# @example  APPLICATION_LIST="billing search" ssh_generate_keys_all
# @requires ssh-keygen
# @danger   See ssh_generate_key.
# @see      ssh_generate_key
# @os       any
ssh_generate_keys_all() {
    local app flags
    if [ -z "${APPLICATION_LIST:-}" ]; then
        log_error "ssh_generate_keys_all: APPLICATION_LIST is empty"
        return 1
    fi
    # zsh does not word-split unquoted parameters; normalise through an array.
    if [ -n "$ZSH_VERSION" ]; then
        eval 'flags=(${=APPLICATION_LIST})'
    else
        eval 'flags=($APPLICATION_LIST)'
    fi
    for app in "${flags[@]}"; do
        ssh_generate_key "$app" || return 1
    done
}

# ------------------------------------------------------------- x forwarding --

# @describe Share this machine's keyboard and mouse with a remote X display over
#           ssh, using x2x.
# @usage    ssh_start_x2x [host] [user] [direction] [display]
# @example  ssh_start_x2x 192.0.2.10 remoteuser east :0.0
# @requires ssh x2x
# @os       any
ssh_start_x2x() {
    local host="${1:?usage: ssh_start_x2x <host> [user] [direction] [display]}" user="${2:-$USER}"
    local direction="${3:-east}" display="${4:-:0.0}"
    log_info "ssh $host -l$user -Y x2x -$direction -to $display"
    ssh "$host" -l"$user" -Y x2x -"$direction" -to "$display"
}

# ------------------------------------------------------------- inventory -----

# @describe Regenerate the ssh config fragment for one AWS account/region using
#           easyssh, then rebuild ~/.ssh/config. Credentials are read from
#           ~/.aws/keys/<account>, which must be a regular file.
# @usage    ssh_generate_host_config [account] [region] [port] [ssh-user]
# @example  ssh_generate_host_config myaccount us-east-1 22 ubuntu
# @requires easyssh aws
# @danger   Sources ~/.aws/keys/<account> into the current shell and replaces
#           $SSH_CONFIG_D/<account>-<region>.config, then runs
#           ssh_refresh_config.
# @see      ssh_refresh_config
# @os       any
ssh_generate_host_config() {
    local account="${1:?usage: ssh_generate_host_config <account> [region] [port] [user]}" region="${2:-us-east-1}"
    local port="${3:-22}" ssh_user="${4:-ubuntu}"
    local keyfile fragment

    has easyssh || { log_error "ssh_generate_host_config needs easyssh on PATH"; return 1; }

    keyfile="$HOME/.aws/keys/$account"
    case "$account" in
        */* | .. | .)
            log_error "ssh_generate_host_config: '$account' is not a plain account name"
            return 1
            ;;
    esac
    if [ ! -f "$keyfile" ]; then
        log_error "ssh_generate_host_config: no credentials file at $keyfile"
        return 1
    fi
    if [ -L "$keyfile" ]; then
        log_warn "$keyfile is a symlink; sourcing it anyway"
    fi

    log_info "sourcing credentials from $keyfile"
    # shellcheck disable=SC1090
    . "$keyfile" || { log_error "failed to source $keyfile"; return 1; }

    export AWS_REGION="$region"
    has aws && aws sts get-caller-identity

    mkdir -p "$SSH_CONFIG_D" || return 1
    fragment="$SSH_CONFIG_D/$account-$region.config"

    log_info "generating $fragment"
    {
        printf '\n'
        easyssh -port "$port" -username "$ssh_user" || return 1
        printf '\n'
    } > "$fragment" || return 1

    cat "$fragment"
    ssh_refresh_config
}

# ------------------------------------------------------- back-compat aliases -
# The long names above are the API. These keep old muscle memory working.
# `ssh_config_refresh` is an alias only — it is never invoked at source time.

alias ssh_config_refresh='ssh_refresh_config'
alias ssh_with_x2x='ssh_start_x2x'
alias get_hosts='ssh_list_hosts'
alias get_hosts_grp='ssh_list_hosts_matching'
alias ssh_keys_generator='ssh_generate_key'
alias ssh_keygen_all='ssh_generate_keys_all'
alias hostgen='ssh_generate_host_config'
