import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// src/content/docs/ is generated by scripts/sync-docs.mjs from ../docs/.
// Nothing in it is hand-edited; it is wiped and rebuilt on every `npm run sync`.
export const collections = {
    docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
